---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-mariadb
spec:
  selector:
    matchLabels:
      app: drupal-mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: drupal-mariadb-persistent-storage
      labels:
        app: drupal-mariadb
    spec:
      containers:
        - image: mariadb:10
          name: mariadb
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: drupal-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: drupal-configmap
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: drupal-configmap
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: drupal-secret
                  key: MYSQL_PASSWORD
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: 100m
              memory: 100M
            limits:
              cpu: 2000m
              memory: 4000M
          volumeMounts:
            - name: drupal-mariadb-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: drupal-mariadb-persistent-storage
          persistentVolumeClaim:
            claimName: drupal-mariadb-pvc
